name: bouncing_balls
version: 1.0.0
description: >-
  Bouncing Balls Animation
author: PeLo
dependencies:
  sprintf: "^4.0.0"
  vector_math: "^2.0.8"
environment:
  sdk: '>=2.0.0 <3.0.0'
packages:
  browser:
    description: browser
    source: hosted
    version: "0.10.0+1"
dev_dependencies:
  build_test: "^0.10.2"
  build_runner: ^1.6.2
  build_web_compilers: ^2.0.0